CC=gcc

.DEFAULT_GOAL := all

all : tcpclient tcpserver

# compile part a
tcpclient : tcpclient.c
						$(CC) -o tcpclient tcpclient.c

tcpserver : tcpserver.c
						$(CC) -o tcpserver tcpserver.c

# TODO: compile part b. check the project write-up for commands

# TODO: compile part c

clean:
		rm tcpclient tcpserver 
		# TODO: may need to expand the line above
